openapi: 3.0.1
info:
  title: Blog Management API
  description: Swagger documentation for your Blog App.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server (Spring Boot or any backend)

paths:
  /api/login:
    post:
      summary: Authenticate admin user
      description: Login API for admin authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: admin123
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  /api/blogs:
    get:
      summary: Get all blogs
      responses:
        '200':
          description: List of all blogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'

    post:
      summary: Add a new blog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blog'
      responses:
        '201':
          description: Blog created successfully

  /api/blogs/{id}:
    get:
      summary: Get blog by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Blog found
        '404':
          description: Blog not found

    put:
      summary: Update existing blog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blog'
      responses:
        '200':
          description: Blog updated

    delete:
      summary: Delete a blog by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Blog deleted successfully

components:
  schemas:
    Blog:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: My First Blog
        author:
          type: string
          example: Priya
        content:
          type: string
          example: This is my first blog post.
        createdAt:
          type: string
          format: date-time
          example: 2025-10-30T10:00:00Z
